### PR TITLE
Support for Hive 3 (#36)

### PR DESCRIPTION
**Pull request by YannByron**
This PR upgrades Hive support to Hive 3.

### CODE REVIEW

**Review by zsxwing — APPROVED** [review]
Thanks! LGTM.

**Comment by zsxwing** [comment]
@YannByron Looks like it's not hard to support both Hive 2 and Hive 3. Do you have time to work on this?

**Comment by YannByron** [comment]
@zsxwing certainly. 
Build connectors for Hive 2 or Hive separately is not graceful. I also ready to make one branch to support two.

**Comment by zsxwing** [comment]
> Building connectors for Hive 2 or Hive 3 separately is not graceful. I also ready to make one branch to support two.

I meant we should be able to build the same jar to support both hive 2 and 3.

**Comment by YannByron** [comment]
@zsxwing I misunderstood. I'll try to take it up.

**Pull request merged**
