### PR TITLE
:arrow_up: Scala 2.13.8

### PR DESCRIPTION
**Pull request by cheleb**

### CODE REVIEW

**Comment by zsxwing** [comment]
Thanks for making the PR. I think we need to upgrade SBT first (#248). Do you have time to work on SBT upgrade? The changes in delta-io/delta ( https://github.com/delta-io/delta/commit/de5cbc1fc5f530a877ce92a298bbf4c72e0926c2 ) is a good reference for this work.

**Comment by cheleb** [comment]
Yes I will take a look asap.

**Comment by cheleb** [comment]
Please https://github.com/delta-io/connectors/pull/253

**Comment by cheleb** [comment]
Any reason why branch-0.3 is not merged into master ?

**Comment by zsxwing** [comment]
> Any reason why branch-0.3 is not merged into master ?

We use branch-0.3 to track potential 0.3.x bug fix releases. Could you work on master instead?

**Comment by cheleb** [comment]
Ok, then I will close this PR.

**Pull request closed without merging**
