### PR TITLE
support to specify partition columns to create external table (#128)

### PR DESCRIPTION
**Pull request by YannByron**

### CODE REVIEW

**Comment by scottsand-db** [comment]
@YannByron is this ready for review? if so, can you please request a review from myself @scottsand-db and @zsxwing

**Comment by YannByron** [comment]
@scottsand-db @zsxwing yes, it's ready. please review it.

**Comment by zsxwing** [comment]
@YannByron can we make it a syntax sugar instead? For example,

```
create external table foo(c1 int)
partitioned by (c2 string)
stored by 'io.delta.hive.DeltaStorageHandler' location '...'
```
should be the same as

```
create external table foo(c1 int, c2 string)
stored by 'io.delta.hive.DeltaStorageHandler' location '...'
```

We don't want to store partition columns into the hive metastore.

**Comment by YannByron** [comment]
@zsxwing 
Storing the partition columns into hive metastore, i think:
1) keep consistency with hive-style table. Users can know whether a delta table is partitioned or not and other related infomations just only via hive-cli;
2) it's useful for some ways accelerating query by skipping replaying delta log, like manifest;
3) backward compatibility. Users can choose one of ddl to create external table.

**Comment by zsxwing** [comment]
There are two reasons we decide to hide the partition information from Hive:
- Hive always puts the partition columns to the end of the table schema. Delta allows to put partition columns in any location of the table schema.
- Delta's partition values need to be read from the transaction logs. The data file path cannot be used to calculate the partition value because Delta allows to use arbitrary file path as long as the partition value in AddFile is correct.

> * keep consistency with hive-style table. Users can know whether a delta table is partitioned or not and other related infomations just only via hive-cli;

This is a great benefit but due to the above reasons we cannot store the partition information in Hive Metastore.

**Comment by YannByron** [comment]
@zsxwing Ok, got it.
If so, the pull request can be closed, and i'll use this as a internal feature.

**Comment by zsxwing** [comment]
Closing the PR. Thanks for the contribution!

**Pull request closed without merging**
