### PR TITLE
Fix hive assembly JAR name

### PR DESCRIPTION
**Pull request by allisonport-db**
Currently creates `hive-assembly-assembly_2.11-0.3.0.jar`

### CODE REVIEW

**Comment by scottsand-db** [comment]
Fixing the double `assembly` makes sense. But now we are prepending `delta-`, too. Shouldn't this PR be paired with a other PRs to update docs (e.g. README, delta.io website, etc)? And we try and merge them all around the same time ...

Let me know.

**Comment by scottsand-db** [comment]
Or can we just keep it as `hive-` instead of `delta-hive-`

**Comment by zsxwing** [comment]
Good catch. Did you fix the file names when uploading them to https://github.com/delta-io/connectors/releases/tag/v0.3.0 ?

**Review by zsxwing — APPROVED** [review]

**Comment by allisonport-db** [comment]
What references in README, or delta.io website? It's currently `delta-hive-assembly` in the README, which is what it was previously.

#198 introduced `hiveAssembly` which changed the sbt command for generating the assembly JAR, and its name.
I already updated the README with the new sbt command in #261 but left the name since I meant to also update this.

**Comment by allisonport-db** [comment]
> Good catch. Did you fix the file names manually when uploading them to https://github.com/delta-io/connectors/releases/tag/v0.3.0 ?

Yep, sorry meant to fix this sooner.

**Comment by scottsand-db** [comment]
> It's currently delta-hive-assembly in the README, which is what it was previously.

Ok sweet, so this change is correct. just double checking :)

**Review by scottsand-db — APPROVED** [review]

**Pull request merged**
